### PR TITLE
Fix copyWith's return type.

### PR DESCRIPTION
**Pull request by domesticmouse**
This is an attempt to fix an issue I am seeing in `dart-services`: https://github.com/dart-lang/dart-pad/issues/1712

### CODE REVIEW

**Review by sigurdm — COMMENTED** [review]
This looks good.
Could you write a test exposing the fix?

**Comment by domesticmouse** [comment]
@sigurdm as the fix is add yet another typecast I'm curious what sort of test you would like over this code? 

I'm also conscious that I am patching the usage of a call point that is slated to go away, as indicated by the `deprecated_member_use` on that line, so I'm figuring this code will get deleted sooner or later.

**Comment by sigurdm** [comment]
Just a test that fails before (probably at compile time) because the return type is wrong - and succeeds after the fix.

In other words: a test that the issue you experienced was fixed, and ensuring we don't regress.

**Comment by domesticmouse** [comment]
Quick question, is there a way of generating code and then rolling the pedantic linters over it?

**Review by parlough — APPROVED** [review]

**Comment by sigurdm** [comment]
Hmm - the linter should be run on generated code from the travis script - I don't think you need to do it programatically.

**Comment by domesticmouse** [comment]
How about I add the `pedantic` package to `protobuf/analysis_options.yaml`? That should be enough to prevent this regressing.

**Comment by sigurdm** [comment]
> Why wasn't this caught by the linter previously?

Good question.

Looking into this, the difference is to be that dartpad uses:
```
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by sigurdm** [comment]
I made the change to protoc_plugin entirely.

Question is if we should land this in master, or only on null_safety as this is a lint-only fix.

@iinozemtsev WDYT?

**Comment by iinozemtsev** [comment]
Sorry, I somehow did not see this earlier. I think merging it into master is fine, I'm going to merge master into null safety in the next few days (I think since github squashes PRs before merge this won't be a real merge, rather a cherry-picking missing commits from master)

**Comment by domesticmouse** [comment]
@sigurdm do you need me to do anything w.r.t fixing up this PR such that all tests pass?

**Pull request merged**
