### PR TITLE
Null safe package:protobuf and null safe code generation

### PR DESCRIPTION
**Pull request by iinozemtsev**
Makes `protobuf` null safe and makes `protoc_plugin` to generate null safe code. `protoc_plugin` itself is not yet migrated to null safety because it depends on `dart_style`. 

Also cannot make `api_benchmark` and `query_benchmark` working yet, as they transitively depend on `fixnum ^0.10.9`, which is incompatible with protobuf dependency on `fixnum ^1.0.0`.

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
Note that for `api_benchmark` and `query_benchmark`, you can override the dependencies using `dependency_overrides`, which should allow you to work around that issue.

**Comment by iinozemtsev** [comment]
I tried various dependency overrides, but couldn't make it working, currently dependency conflict arises because of this:

```
benchmark ->  protobuf -> fixnum ^1.0.0-nullsafety.0
benchmark -> build_runner -> code_builder -> built_value -> fixnum ^0.10
```
I tried using built_value from git, but that one depends on fixnum ^1.0.0, which does not seem to include 1.0.0-nullsafety.0

**Comment by sigurdm** [comment]
> I tried various dependency_overrides

Hmm I don't think `query_benchmark` relies on build_runner. Here is the pubspec:
```
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  protobuf:

dev_dependencies:
  protoc_plugin:
    path: "../protoc_plugin"

dependency_overrides:
  protobuf:
    path: "../protobuf"
```

I am able to get a resolution.

```
> pub get
Resolving dependencies... 
> fixnum 1.0.0-nullsafety.0 (was 0.10.11)
> protoc_plugin 19.2.0 from path ../protoc_plugin (was 19.1.0 from path ../protoc_plugin)
Warning: You are using these overridden dependencies:
! protobuf 2.0.0-nullsafety.0 from path ../protobuf
Downloading fixnum 1.0.0-nullsafety.0...
Changed 3 dependencies!
```

For the api benchmark I think you **can** trick the system with a dependency override:
```
sigurdm@sigurdm-macbookpro2 ~/p/p/api_benchmark (null_safety)> git diff
diff --git a/api_benchmark/pubspec.yaml b/api_benchmark/pubspec.yaml
index dc0cfd8..384f7ea 100644
--- a/api_benchmark/pubspec.yaml
+++ b/api_benchmark/pubspec.yaml
@@ -23,3 +23,4 @@ dev_dependencies:
 dependency_overrides:
   protobuf:
     path: "../protobuf"
+  fixnum: ^1.0.0-nullsafety.0
```

```
> pub get
Resolving dependencies... 
> protoc_plugin 19.2.0 from path ../protoc_plugin (was 19.1.0 from path ../protoc_plugin)
Warning: You are using these overridden dependencies:
! fixnum 1.0.0-nullsafety.0
! protobuf 2.0.0-nullsafety.0 from path ../protobuf
Changed 3 dependencies!
```

**Comment by iinozemtsev** [comment]
Thanks a lot Sigurd, I'll open a new PR soon to merge master branch into null safety and will also try fixing benchmarks

**Pull request merged**
