### PR TITLE
Added constructors for messages

### LINKED ISSUE #155: named arguments to set fields in a constructor
I am not sure if this feature request is worth it, but I wanted to share the idea, so here it is:

What if we take generated messages and make a constructor that takes as arguments the actual fields from the proto buff? for example:

``` proto
message A {
  required someField = 1;
  optional otherField = 2;
}
```

generates:

``` dart
class A extends GeneratedMessage {
  A.filled(this.someField, {this.otherField});
}
```

I just often see patterns where developers have all the data they need to fill in, and end up writing code like:

``` dart
  new A()
      ..someField = a
      ..otherField  = b
```

instead of:

``` dart
  new A(a, otherField: b)
```

### PR DESCRIPTION
**Pull request by Kavantix**
Fixes #155

### CODE REVIEW

**Review by sigurdm — CHANGES_REQUESTED** [review]
This is a nice addition, greatly improving the user-experience.

However many tests are still failing. Try to look into the travis logs...

**Review by sigurdm — COMMENTED** [review]
@rakudrama do you have a feeling how this would affect size of the generated code?
My guess would be that the constructor would be inlined everywhere - maybe we would have to try it.

**Comment by Kavantix** [comment]
The tests also fail on the current master so not sure what's my part in this

I'm also considering adding the same thing to the copyWith (and then make the current function parameter optional position)
Would that be a good addition for this pr?

**Comment by sigurdm** [comment]
I just ran all tests on master and they don't fail.

You'll have to add a line:
```
dependency_overrides: {protobuf: {path: ../protobuf}}
```

to protoc_plugin/pubspec.yaml

Followed by `pub get`

to test it locally.

**Comment by Kavantix** [comment]
Ah i see, using that there are still tests failing on master though.
But if I only run the tests that start with `message` then they indeed pass on master and the golden file was just not updated yet so I did.

**Comment by sigurdm** [comment]
What tests are failing on master?

**Comment by Kavantix** [comment]
Nvm not all needed files were generated.
Fixed the last error now

**Comment by Kavantix** [comment]
Hmm some more golden files are failing, I'll update these later today, tbc

**Comment by Kavantix** [comment]
Should be ready to merge now

**Review by sigurdm — APPROVED** [review]

**Comment by osa1** [comment]
Port to internal in cl/449707130.

**Comment by rakudrama** [comment]
> @rakudrama do you have a feeling how this would affect size of the generated code? My guess would be that the constructor would be inlined everywhere - maybe we would have to try it.

I expect this change to be quite detrimental to code size.
I'm sad I didn't notice your question earlier.
I would have suggested not doing this.

**Pull request merged**
