### PR TITLE
Emit binary coded descriptors from dart protoc_plugin

### PR DESCRIPTION
**Pull request by iinozemtsev**
Port of an internal change

These descriptors contain extensions, and thus can be used to reflect over the options given to the descriptor

Fixes: https://github.com/dart-lang/protobuf/issues/341

### CODE REVIEW

**Comment by iinozemtsev** [comment]
Please review only the latest commit, as the first 3 commits correspond to other pending PRs

**Comment by iinozemtsev** [comment]
to make analyzer happy, I've also added writing `'// ignore_for_file: deprecated_member_use_from_same_package'` from file_generator.dart for pbjson files

**Comment by iinozemtsev** [comment]
leading_underscores_test shows that this one needs more work both externally and internally: name generation in writeBinaryDescriptor is not efficient enough, also deprecation warning is confusing

**Comment by iinozemtsev** [comment]
Comparing to an internal version, there are a few extra improvements

- generate deprecation warning for message and service descriptors
- use exact descriptor field names in deprecation annotation descriptors
- disambiguate names and handle leading underscores correctly

Some non-visible changes:
- extract common function `lowerCaseFirstLetter`
- more fine-grained control for ignored  lints in generated files

I'll also prepare the same change for a null safety branch and then update internal version as well

**Review by sigurdm — APPROVED** [review]
Awesome!
LGTM

**Comment by sigurdm** [comment]
No - not expected - not sure what is going on.
Trying one more restart.

**Comment by iinozemtsev** [comment]
Rebased on top of enabling github actions, will wait for results and merge when passes

**Comment by jmin911** [comment]
Is there a command-line parameter to enable this?  This merge is published in plug-in version 19.3.1.  I am using the latest plug-in version (20.0.1).  The generated Dart code does not contain the custom options in descriptors.  However in generated Python code, I can see the binary encoded descriptors.

**Pull request merged**
