### PR TITLE
Avoiding argument_type_not_assignable, return_of_invalid_type

### PR DESCRIPTION
**Pull request by domesticmouse**
PTAL @sigurdm

### CODE REVIEW

**Comment by domesticmouse** [comment]
@rakudrama I've dropped the `as` clause, adding `return_of_invalid_type` to the `ignore_for_file` line instead.

**Comment by sigurdm** [comment]
> It would be much better to make GeneratedMessage generic. 

I should go and revive https://github.com/dart-lang/protobuf/pull/180 ...

**Comment by domesticmouse** [comment]
Is this safe to land?

**Comment by domesticmouse** [comment]
Cool, thanks. I'll roll a follow up PR to bump version numbers in preparation for a pub push.

**Comment by domesticmouse** [comment]
(I don't have rights to merge this, btw =)

**Pull request merged**
