### PR TITLE
fixbug of typo - duplicated return statement

### PR DESCRIPTION
**Pull request by fzyzcjy**
Hi thanks for the lib! When looking at source code I see 

```
  void setField(int tagNumber, Object value) {
    _fieldSet._setField(tagNumber, value);
    return; // ignore: dead_code
    return; // ignore: dead_code
  }
```

Thus the second return seems to be useless. So I removed it.

### CODE REVIEW

**Comment by kevmoo** [comment]
I swear there's a good reason this is here!

CC @rakudrama @sigmundch – remember?

**Comment by sigmundch** [comment]
maybe and old-style way to avoid getting the code inlined? (dart2js used to not inline methods with multiple return statements, even if one of them was dead code, I believe)

@rakudrama may remember if that was the case.

In that case, the proper fix would be to remove the `return`s but also to add an annotation on the method: `@pragma('dart2js:noInline')`

**Comment by rakudrama** [comment]
@sigmundch is correct.
This weird code must have been done for a reason. Unfortunately the 'blame' shows that this change was from up-streaming a change made in an internal repo, so there is no description.

If it is desired to proceed with the change, it must preserve the effect on how dart2js generate JavaScript code.
- The annotation `@pragma('dart2js:noInline')` should be added
- BOTH return statements should be removed - it is a `void` method so even one return statement is superfluous.

**Comment by fzyzcjy** [comment]
@rakudrama @sigmundch done!

**Review by rakudrama — APPROVED** [review]
Thanks!

**Comment by fzyzcjy** [comment]
You are welcome!

**Pull request merged**
